### ISSUE TITLE
为什么 COUNT_FINISH 是 1？

### ISSUE THREAD

**Issue by Wonicon** [NJU-CS-SYS/ArchLab2015#11]
[status.vh 第 11 行](https://github.com/NJU-CS-SYS/ArchLab2015/blob/b5eef50cebb5eaf2472d38632c298d405dbba6ee/src/io/cache/status.vh#L11)

假设只发生了 I-cache miss，在下个存储器周期C中，状态从 STAT_NORMAL 转移到 STAT_IC_MISS，且 counter 赋值成 0. 在周期 C 中，cache_control 生成 counter_next 信号为 1. 那么在下次存储器有效(ram_rdy)的周期 D 中，cache_manage_unit 会将 counter 更新成 1，然后 cache_control 中观察到 counter_in 为 CONUT_FINISH，生成下一状态为 STAT_NORMAL。于是只写了 0 和 1 两个字？

**Comment by shinezyy** [comment]
现在我把cache与ram之间的读写改成整块读写了，因为user interface已经封装了burst read；
finish_counter设置为1是因为现在的ddr2 user interface只支持128bit的读写，需要分两次进行。
如果后面我配置出了256bit的user interface，finish_counter将会被设置为0（其实可以去掉了）。

**Comment by Wonicon** [comment]
那后面一整块的 +1 逻辑是不是可以删掉了？
