### ISSUE TITLE
tag_out 实际上都来自第 0 路？

### ISSUE THREAD

**Issue by Wonicon** [NJU-CS-SYS/ArchLab2015#12]
见[这里](https://github.com/NJU-CS-SYS/ArchLab2015/blob/b5eef50cebb5eaf2472d38632c298d405dbba6ee/src/io/cache/cache_2way.v#L181)

**Comment by shinezyy** [comment]
It is typo. When cmp is active, tag_out is meaningless....
But it seems that code review is deadly important to me...
